### PR TITLE
feat: add ability to deactivate auto update

### PR DESCRIPTION
**Pull request by marlontrapp**
Adding the ability do deactivate the auto update timer.

### CODE REVIEW

**Review by martini97 — APPROVED** [review]

**Review by ruimartin — APPROVED** [review]
The code LGTM. But why not just use a big update interval? 
There are some users who almost never refresh the page, and it may take time to completely kill a feature using the feature flag for these users.

**Comment by marlontrapp** [comment]
> 

The first thing I did on Alice to fix the refresh erasing the screen of the user was use a big interval, but it looks like a work around instead of deactivating it. Besides that, if the user takes too much time the credential will be revoked and one must reload the page.

**Review by rivajunior — APPROVED** [review]
🚀

**Pull request merged**
